# Generated by Django 5.2.10 on 2026-01-31 13:48

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="nickname",
        ),
        migrations.AddField(
            model_name="customuser",
            name="fullname",
            field=models.CharField(
                default=datetime.datetime(2026, 1, 31, 13, 48, 43, 982105, tzinfo=datetime.timezone.utc),
                help_text="Иванов Иван Иванович",
                max_length=50,
                verbose_name="Ф.И.О.",
            ),
            preserve_default=False,
        ),
    ]
