# Generated by Django 5.2.10 on 2026-01-29 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "fullname",
                    models.CharField(help_text="Иванов Иван Иванович", max_length=300, verbose_name="Ф.И.О."),
                ),
                (
                    "uniquename",
                    models.CharField(max_length=50, unique=True, verbose_name="Уникальный идентификатор сотрудника"),
                ),
                ("position", models.CharField(help_text="Сотрудник", max_length=300, verbose_name="Должность")),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="employees/image", verbose_name="Фото")),
                ("work_phone", models.IntegerField(blank=True, null=True, verbose_name="Служебный телефон")),
                ("description", models.TextField(verbose_name="Примечание")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создание учетной карточки")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата последнего обновления")),
                ("is_active", models.BooleanField(default=True, verbose_name="Статус активности")),
                (
                    "header",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Руководитель сотрудника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
