# Generated by Django 5.2.10 on 2026-01-29 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Краткое описание задачи", max_length=200, verbose_name="Наименование задачи"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Подробное описание задачи", null=True, verbose_name="Описание задачи"
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        help_text="Дата, к которой задача должна быть выполнена", verbose_name="Срок выполнения"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "К выполнению"),
                            ("in_progress", "В работе"),
                            ("review", "На проверке"),
                            ("done", "Выполнено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="todo",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("medium", "Средний"),
                            ("high", "Высокий"),
                            ("critical", "Критический"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата завершения")),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Сотрудник, ответственный за выполнение задачи",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="employees.employee",
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Задача, от которой зависит текущая",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="tasks.task",
                        verbose_name="Родительская задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["-created_at"],
            },
        ),
    ]
