# Generated by Django 5.2.10 on 2026-02-05 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец задачи",
            ),
            preserve_default=False,
        ),
    ]
